image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: open-browser
  - port: 3002
    onOpen: open-browser
  - port: 6379 # Redis
    onOpen: ignore

tasks:
  - command: redis-server
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - command: nvm install 13
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
  - command: > # ENV vars
      gp env REACT_APP_API_ENDPOINT=http://localhost:3000
  - command: > # Start API
      cd api
      cp .env.gitpod .env
      yarn dev
  - command: > # Start Dashboard
      cd dashboard
      yarn
      PORT=3001 SASS_PATH=./node_modules yarn start
  - command: > # Start Widget
      cd widget
      yarn
      PORT=3002 yarn start

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
    # add a check to pull requests (defaults to true)
    addCheck: true