image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000 # API
    onOpen: open-browser
  - port: 3001 # Dashboard
    onOpen: open-browser
  - port: 3002 # Widget
    onOpen: open-browser
  - port: 6379 # Redis
    onOpen: ignore

tasks:
  - command: > # Start Redis
      redis-server
  - command: > # Start MongoDB
      mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - command: > # Start API
      nvm install 13 &&
      cd api &&
      cp .env.gitpod .env &&
      yarn --mutex file:/tmp/.yarn-mutex &&
      yarn dev
  - command: > # Start Dashboard
      cd dashboard &&
      yarn --mutex file:/tmp/.yarn-mutex &&
      PORT=3001 SASS_PATH=./node_modules yarn start
  - command: > # Start Widget
      cd widget &&
      yarn --mutex file:/tmp/.yarn-mutex &&
      PORT=3002 yarn start

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
    # add a check to pull requests (defaults to true)
    addCheck: true