[build]
  command = "cd dashboard && yarn build"
  publish = "build/"

[template.environment]
  SASS_PATH = "./node_modules"
  STREAM_APP_ID = "YOUR STREAM APP ID"
  STREAM_API_KEY = "YOUR STREAM API KEY"